### ISSUE TITLE
Kata

### ISSUE THREAD

**Issue by FakeSkdr** [m6-workshops/kata-1-100-team#22]
Kata seems depressed, should we call a doctor?

**Comment by outadoc** [comment]
Probably :(

**Comment by MarcAurel** [comment]
We don't have time to fix this before going to production... 😢

**Comment by outadoc** [comment]
![https://giphy.com/gifs/mrw-song-myself-Ty9Sg8oHghPWg](https://media.giphy.com/media/Ty9Sg8oHghPWg/giphy.gif)
